CMS_OAUTH2_SECRET: QnuI5wdLNqDuJjJZisCeTQ2g
ID: PNau6o2kAJCHpjixH3zSnrwJ
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEpAIBAAKCAQEAuMiy+TAK65mpyl5TnjV1w+oWbA3zPL2EdtUcQ07nN20q+Rsq

  q6XES2jtlhKjxgkmv9ya6e4L+pAlvxoxLsflEqMoVS74innR/9S12iCia0JpuxcG

  5vzF7rSWly590vyRx1sMW6aXj0UOw7BbfqKP2eD9LtpMPMBh3+1yK/soXZFNtbeW

  mf2vkCa98CNfRIfP7BYIC9vkZWihIW3qA8XOuz5Wgs/hWhq+K9EYbwMJEy2kH10K

  M2T2jVNvVTFe60piyDx+JN7gUJRfo7qZGaxQ6SAHISl8eK5fTQX1dcgKNJEf14iZ

  M9lRpOyiokgAl4f8fFbAAsaCMTV5Nnz7VsWZuwIDAQABAoIBAAQ2Xw4bMESKrjo0

  yEc1BMhAj95Kux7JWzmyRgCqzc6PqIkhO2nKT51AeRoQtrcPAlkhWE645IEDxDiF

  ClX8rJYuLf8zIOtXN5hTawnb8JftXaesMLYXURPN/hjYMHoc093tj2yPcakMc/e2

  D3/liM34uQzWYSKJaDHIoe+qvBLV8TLX2GhFgxugPG52hpKLl8IvV79KM7D00b65

  5jTIN/ywyBgMwFc51e5ffts85ABn3a7QwJ7ue2SOwYO/XWilWb9+/bpOYe7jYGy4

  pFVqk6qP/gW7BdSt+/BA5JpJUdIQNIkpEwqDYnOhiIOT4oyWt+iY9oSXgdh8+kfU

  OV6XvaECgYEAyMTq0alDHF6wWP9otf+zdoajMWZ4tFRvC79tlxr9fJxBYYSMEgE+

  7GwfYpnL3sY9upIZZqNMTEna2sx8TIcwXlWQ2vo0uSPj4D5Ozp01i1HVZK2dEB8z

  0eBykWd2zjxk11nrcWBC4s6cHMiw97jninFsYIbEoMjedmFwM8mU33kCgYEA654H

  gAlq1MwibARxJSTt//0T68kJkujKg0whEE7V5au1MomZwwN+v4y6wKx6H3Re7usX

  Lxj9MXQcCacOqYWOeCMJVB9WJkV7fwlkwZDexLXZyOG4XVJQSz3TVG6haKBvsXeD

  E1W+BXP2Bix0vhQ2zrCijoLbbDQbl213f3GVcdMCgYEAqgcKjtD4Avi2BEkZlric

  dc6EOnv70UyIVryhxQyYjIWQYVPtg/oGHhdbZRe2rk3ZTT4ZwPCe1yTc8dunkPAU

  qG9yo+Ct8fVRMUHTX+uHwxtky0S09UhXjHC21il3ViWTiUWfvX62Znpvf3j/VmwD

  ux1fmUfJEhnLPRo7+b/IEpECgYEAndqDBdnJVAXrbdjQAOWr+hwQs6A9pMoHm01u

  vWFD1ppiTBh6BngZ+7UKDTnAm8A4NfMU1j30q6QxgJoGrbZHy98VSeGwsvVMFsEx

  Wql3RezbmsT24rbaCn7CTcfMpa8PBaOfEl4Yb8jP5DT2hb4/NdyLG9U5slV6wsnZ

  DG4JhHcCgYA/LlpiSL1Yc1zzS2mNq2olf8EiNn9YieYUa50F+TLPvJWWWZbLwCRn

  wzhFaLm81HNKt/tIW7b7Urg6XUbbH2oDj8bePyP++Z+ZVY2xDfsmvGS0pSEWbgc5

  qx5ds1sllgtx4TuSapLCNoRK44eBk5ApxsV5KB0mjhTdxzY/mKAzgQ==

  -----END RSA PRIVATE KEY-----'
MEILISEARCH_API_KEY: 8409083f34402c541580f1dec6174b90ec7bd22108120c53a69ae9ae091897f7
MEILISEARCH_API_KEY_UID: e0cb5f62-dba3-40cc-800f-986a45263b3f
MEILISEARCH_MASTER_KEY: 2BpyzGCFcGpz7GH1GuUAbwSO
MYSQL_ROOT_PASSWORD: uZLj1bRl
OPENEDX_MYSQL_PASSWORD: W8hedofV
OPENEDX_SECRET_KEY: i6TCkGN0AqtaZQPAk2rOo2V9
PLUGINS:
- catalog_extensions
- indigo
- mfe
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
- https://overhang.io/tutor/contrib
